config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :home, only: [:index]
  resources :cocktail_details, only: [:index, :show]
  resources :ingredients, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktail_details_controller.rb
class CocktailDetailsController < ApplicationController
  def index
    client = Cocktail::Api::Client.new
    @cocktails = client.search_cocktail_name(params[:id])
  end

  def show
    client = Cocktail::Api::Client.new
    @informations = client.cocktail_info(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    client = Cocktail::Api::Client.new
    @randoms = client.random_drinks
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    client = Cocktail::Api::Client.new
    @ingredients = client.search_ingredient_name(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_details_helper.rb
module CocktailDetailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktail_details/index.html.erb
<div class="row">
    <% @cocktails["drinks"].each do |cocktail| %>
        <div class="col-sm-4">
            <div class="card cocktail mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src=<%= cocktail["strDrinkThumb"]%> class="tbl-img">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <div class="row s-font">
                                        <div class="col right">
                                            <b>NAME :</b>
                                        </div>
                                        <div class="col left">
                                            <%= link_to cocktail["strDrink"], cocktail_detail_path(cocktail["idDrink"]) %>
                                        </div>
                                    </div>
                    
                                    <div class="row s-font">
                                        <div class="col right">
                                            <b>CATEGORY :</b>
                                        </div>
                                        <div class="col left">
                                            <%= cocktail["strCategory"]%>
                                        </div>
                                    </div>
                    
                                    <div class="row s-font">
                                        <div class="col right">
                                            <b>GLASS :</b>
                                        </div>
                                        <div class="col left">
                                            <%= cocktail["strGlass"]%>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
</div>


        

app/views/cocktail_details/show.html.erb
<div class="card random center">
    <% @informations["drinks"].each do |information|%>
        <div class="card-header">
            <h4><%= link_to information["strDrink"], cocktail_detail_path(information["idDrink"]) %></h4>
        </div>

        <img src=<%= information["strDrinkThumb"]%>>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row">
                    <div class="col right">
                        <b>CATEGORY :</b>
                    </div>
                    <div class="col left">
                        <%= information["strCategory"]%>
                    </div>
                </div>

                <div class="row">
                    <div class="col right">
                        <b>GLASS :</b>
                    </div>
                    <div class="col left">
                        <%= information["strGlass"]%>
                    </div>
                </div>
            </li>

            <li class="list-group-item">
                <div class="card-body">
                    <h5 class="card-title">INSTRUCTIONS</h5>
                    <p class="card-text"><%= information["strInstructions"]%></p>
                </div>
            </li>
        </ul>

        <div class="card-body">
            <h5 class="card-title">INGREDIENTS</h5>
            <div class="row">
                <div class="col-5 right bi-caret-right-fill"><b></b></div>
                <div class="col-7 left"> <%= information["strMeasure1"]%> <%= link_to information["strIngredient1"], ingredient_path(information["strIngredient1"]) %> </div>
            </div>

            <%if information["strIngredient2"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure2"]%> <%= link_to information["strIngredient2"], ingredient_path(information["strIngredient2"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient3"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure3"]%> <%= link_to information["strIngredient3"], ingredient_path(information["strIngredient3"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient4"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure4"]%> <%= link_to information["strIngredient4"], ingredient_path(information["strIngredient4"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient5"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure5"]%> <%= link_to information["strIngredient5"], ingredient_path(information["strIngredient5"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient6"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure6"]%> <%= link_to information["strIngredient6"], ingredient_path(information["strIngredient6"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient7"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure7"]%> <%= link_to information["strIngredient7"], ingredient_path(information["strIngredient7"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient8"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure8"]%> <%= link_to information["strIngredient8"], ingredient_path(information["strIngredient8"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient9"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure9"]%> <%= link_to information["strIngredient9"], ingredient_path(information["strIngredient9"]) %> </div>
                </div>
            <%end%>

            <%if information["strIngredient10"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right-fill"><b></b></div>
                    <div class="col-7 left"> <%= information["strMeasure10"]%> <%= link_to information["strIngredient10"], ingredient_path(information["strIngredient10"]) %> </div>
                </div>
            <%end%>
        </div>
    <%end%> 
</div

app/views/home/index.html.erb
<div class="card random center">
    <% @randoms["drinks"].each do |random|%>
        <div class="card-header">
            <h4>FEATURED DRINK</h4>
        </div>

        <img src=<%= random["strDrinkThumb"]%> >

        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <div class="row">
                    <div class="col right">
                        <b>NAME :</b>
                    </div>
                    <div class="col left">
                        <%= link_to random["strDrink"], cocktail_detail_path(random["idDrink"]) %>
                    </div>
                </div>
                <div class="row">
                    <div class="col right">
                        <b>CATEGORY :</b>
                    </div>
                    <div class="col left">
                        <%= random["strCategory"]%>
                    </div>
                </div>

                <div class="row">
                    <div class="col right">
                        <b>GLASS :</b>
                    </div>
                    <div class="col left">
                        <%= random["strGlass"]%>
                    </div>
                </div>
            </li>

            <li class="list-group-item">
                <div class="card-body">
                    <h5 class="card-title">INSTRUCTIONS</h5>
                    <p class="card-text"><%= random["strInstructions"]%></p>
                </div>
            </li>
        </ul>
        
        <div class="card-body">
            <h5 class="card-title">INGREDIENTS</h5>
            <div class="row">
                <div class="col-5 right bi-caret-right"><b></b></div>
                <div class="col-7 left"><%= random["strMeasure1"]%> <%= link_to random["strIngredient1"], ingredient_path(random["strIngredient1"]) %></div>
            </div>

            <%if random["strIngredient2"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure2"]%> <%= link_to random["strIngredient2"], ingredient_path(random["strIngredient2"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient3"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure3"]%> <%= link_to random["strIngredient3"], ingredient_path(random["strIngredient3"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient4"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure4"]%> <%= link_to random["strIngredient4"], ingredient_path(random["strIngredient4"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient5"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure5"]%> <%= link_to random["strIngredient5"], ingredient_path(random["strIngredient5"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient6"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure6"]%> <%= link_to random["strIngredient6"], ingredient_path(random["strIngredient6"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient7"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure7"]%> <%= link_to random["strIngredient7"], ingredient_path(random["strIngredient7"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient8"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure8"]%> <%= link_to random["strIngredient8"], ingredient_path(random["strIngredient8"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient9"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure9"]%> <%= link_to random["strIngredient9"], ingredient_path(random["strIngredient9"]) %></div>
                </div>
            <%end%>

            <%if random["strIngredient10"] != nil%>
                <div class="row">
                    <div class="col-5 right bi-caret-right"><b></b></div>
                    <div class="col-7 left"><%= random["strMeasure10"]%> <%= link_to random["strIngredient10"], ingredient_path(random["strIngredient10"]) %></div>
                </div>
            <%end%>
        </div>
    <%end%>
</div>

app/views/ingredients/show.html.erb
<div class="row">
    <div class="col-4">
        <div class="card ing-img center">
            <h1><%= @ingredients["ingredients"][0]["strIngredient"]%></h1>
            <img src="https://www.thecocktaildb.com/images/ingredients/<%= @ingredients["ingredients"][0]["strIngredient"]%>-medium.png">
            <%= link_to ' Back', request.referrer, class:"delete-icon bi-arrow-left-circle-fill" %>
        </div>
    </div>
   
    <% if @ingredients["ingredients"][0]["strDescription"] != nil%>
        <div class="col-8">
            <div class="card ing-details center">
                <div class="card-header">
                    <h4><%= @ingredients["ingredients"][0]["strIngredient"]%> Details</h4>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col right">
                                <b>TYPE :</b>
                            </div>
                            <div class="col left">
                                <%= @ingredients["ingredients"][0]["strType"]%>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col right">
                                <b>IS ALCOHOL? :</b>
                            </div>
                            <div class="col left">
                                <%= @ingredients["ingredients"][0]["strAlcohol"]%>
                            </div>
                        </div>
                    </li>

                    <li class="list-group-item">
                        <div class="card-body">
                            <h5 class="card-title">DESCRIPTION</h5>
                            <p class="card-text"><%= @ingredients["ingredients"][0]["strDescription"]%></p>
                        </div>
                    </li>
                </ul>
            </div
        </div>
    <%end%>
</div>


        

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><%= image_tag "logo.png", class: "logo" %></a>
        <div>
            <%= form_with url: cocktail_details_path, method: :get, html: {class: "container-fluid"} do |form| %>
                <div class="input-group">
                <span class="input-group-text bi-search" id="basic-addon1"></span>
                <%= form.text_field :id, class:"form-control"%>
                <%= form.submit "Search", class:"btn btn-custom" %>
                </div>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container center">
      <%= yield %>
    </div>
  </body>

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</html>